set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports {clock}]; # Center Button
create_clock -add -name sys_clk_pin -period 40.000 -waveform {0 20.000} [get_ports {clock}]

set_input_delay -clock [get_clocks sys_clk_pin] 1.0 [get_ports * -filter {DIRECTION == IN && NAME !~ "clock"}]
set_output_delay -clock [get_clocks sys_clk_pin] 2.0 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]

set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {en_5}]; # Left Button

#create_clock -add -name sys_clk_en -period 40.000 -waveform {0 20.000} [get_ports {en_5}]

#set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {mux_sel_5}]; # Center Button
#set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {reset}]; # Left Button
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports {done}]; # CA

#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[31]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[30]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[29]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[28]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[27]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[26]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[25]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[24]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[23]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[22]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[21]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[20]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[18]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[17]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_A[0]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[31]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[30]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[29]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[28]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[27]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[26]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[25]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[24]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[23]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[22]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[21]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[20]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[18]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[17]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_B[0]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_from_R0[0]}]

