webtalk_init -webtalk_dir /home/shivamtyagi/baseline_multiplier/baseline_multiplier.sim/sim_1/impl/func/xsim/xsim.dir/cla_TB_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May  8 15:24:31 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e69bb698-ff4f-4a07-b05c-95d6bff1b540" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "90c58691ad694bd88bf5b521ec1cad12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "38" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2207.566 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key saif -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4000020 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "77.84_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "146240_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2101273918 -regid "" -xml /home/shivamtyagi/baseline_multiplier/baseline_multiplier.sim/sim_1/impl/func/xsim/xsim.dir/cla_TB_func_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/shivamtyagi/baseline_multiplier/baseline_multiplier.sim/sim_1/impl/func/xsim/xsim.dir/cla_TB_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/shivamtyagi/baseline_multiplier/baseline_multiplier.sim/sim_1/impl/func/xsim/xsim.dir/cla_TB_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
